# -*- coding: utf-8 -*-
"""session8_assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11PiOF9_n9_z7t9C1xJT-93cqN6XKn0BF
"""

# write a python program to subtract two numbers 
 num1 = 1.5
 num2 = 6.3
 sum = num1 - num2
 print(f' Diff: {sum}')

#write a python program to print first 10 natural numbers

i = 0
while i <= 10:
    print(i)
    i += 1

#write a python program to  and print the total number of digits in a number

num = 75869
count = 0
while num != 0:
    num //= 10
    count+= 1
print("Total digits are: ", count)

#write a python function to  take a list and return the reverse of it
def rev_list(in_list):
  start = len(in_list) - 1
  stop = -1
  step = -1
  for i in range(start, stop, step) :
      print(in_list[i])
  return in_list

# write a python function to multiply two user provided numbers and return the product
def mult_two_numbers(num1, num2):    
  prod = num1 * num2    
  return prod

# write a program to find and print the largest among three numbers
num1 = 10
num2 = 12
num3 = 14
if (num1 >= num2) and (num1 >= num3):   
  largest = num1
elif (num2 >= num1) and (num2 >= num3):   
  largest = num2
else:   
  largest = num3
print(f'largest:{largest}')